# Generated by Django 5.1.3 on 2025-02-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
